quarkus:
  http:
    port: 8080

adapter:
  excel:
    source: sample-routes.xlsx
    sheet: routes
  execution:
    mock-enabled: true
    connect-timeout-ms: 3000
    read-timeout-ms: 5000

adapter-dsl:
  transforms:
    orderPayload:
      type: object
      fields:
        countryCode:
          source: "$.path.country"
          optional: true
        shopReference:
          source: "$.path.shopId"
        promoCode:
          source: "$.path.promoCode"
        customerId:
          source: "$.customerId"
        amount:
          source: "$.amount"
        currency:
          source: "EUR"
    compactOrderPayload:
      type: object
      fields:
        countryCode:
          source: "$.path.country"
          optional: true
        customerId:
          source: "$.customerId"
        amount:
          source: "$.amount"
